---
title: "10-15-2"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##基本改(向量)
```{r}
x<-1
```
```{r}
x1<-c(1,2,3)
```
```{r}
x2<-c(TRUE,FALSE,TRUE)
```
c() 是一個函數，。用以形成一個向量變數

##統計量1
```{r}
x<-c(2,3,4,6,7,4,3,2,9)  #column
mean(x)  #平均數
median(x)  #中位數
var(x)  #變異數
quantile(x)  
sd(x)
fivenum(x)
range(x)
min(x)
max(x)
```
##統計量2
```{r}
x<-runif(40)
length(x)  #一個向量多長；越接近0.5數據越集中、不分散
mean(x)  #平均數
median(x)  #中位數
var(x)  #變異數
quantile(x)  
sd(x)
fivenum(x)
range(x)
min(x)
max(x)
```
##統計量3
```{r}
x<-c(1,2,3)
y<-c(1,2)
```
##統計量4
```{r}
x <- seq(0, 1, by = 0.3)
y <- seq(0, 1, by = 0.2)
x
y
x[2]  #x的第2個數字
x[0]
x[6]  #遺失值
x[0]
y[4] == 1 - x[3]  #
```
##統計量5
```{r}
#我要知道誰>5 ; >=0.5
x <- seq(0, 1, by = 0.3)
x>=0.5
```
##統計量6
```{r}
x1<-c(T,T,F,T)
x2<-c(F,F,T,T)
x1|x2
x1&x2
```
##統計量7
```{r}
x<-c(1,2,3,4,5,6,7)
x[3]
#要拿1.3.5.7(法1)
idx<-c(1,3,5,7)
x[idx]
#要拿1.3.5.7(法2)
x[c(1,3,5,7)]
```
##統計量8
```{r}
x<-c(1,2,3,4,5,6,7)
x[3]
#要拿1.3.5.7(法1)
idx<-c(1,3,5,7)
x[idx]
#要拿1.3.5.7(法2)
x[c(1,3,5,7)]

x[-1]#不要第1
length(x[-7])#把第7拿掉後剩下的字串長度
```
##統計量(老師要出問題了喔！#1)
```{r}
#大小為20的均勻亂數平均值100個
for ( t in 1:100){
  x<-sample(100,20)
  x1<-mean(x)
  print(x1)
}
```
##統計量(老師要出問題了喔！#2)
```{r}
#大小為4000的均勻亂數平均值100個
for ( t in 1:100){
  x<-sample(1000,20)
  x1<-mean(x)  
  x2=c(x1)
}  
mean(x2)
```