---
title: "10-22-2"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown
#雜記-1
```{r}
x<-seq(1,2,5)
x
x1<-seq(1,3,length=8)
x1

x2<-c(T,F)
x3<-c(F,T,T)
x2|x3
```
#雜記-2(基礎抽樣)
```{r}
A<-c("A","B","C","D")
B<-A
C<-c("A","C","C","E")
which(A!=C)
A[A==C]
A[c(1,2,4,3,1)]
```
#雜記-3(基礎抽樣which)
```{r}
A<-c("A","B","C","D")
B<-A
C<-c("A","C","C","E")
temp<-1:length(A)#產生1-A
temp[A==C]
which(A==C)
#上下相同答案
```
#雜記-4(基礎抽樣which)
```{r}
A<-c("A","B","C","D")
B<-A
C<-c("A","C","C","E")
temp<-1:max(length(A),length(C))
temp[A!=C]
which(A!=C)
#上下相同答案
```
#雜記-5(要畫圖了喔!)
```{r}
x=1:5
plot(x)
x1=5:10
#一個參數plot(y)、2個參數plot(x,y)
plot(1:length(x1),x1)#(x,y)
plot(x1,type="s")
plot(x1,type="S")

y<-rnorm(100,5,2)#如果(,?) ?不填就是正常
plot(y,type="o")
plot(y,type="p")
```
#雜記-6(要畫圖了喔!)
```{r}
x2<-rnorm(100,5,2)
plot(x2,y)
plot(x2,y,xlab = "XXX",ylab="YYY",main = "title")
plot(sin,-pi,2*pi,20)
plot(cos,-pi,2*pi,20)
```
#雜記-7(要畫圖了喔!)
```{r}
cos_sin<-function(from,to)
{
  xsmp<-seq(from,to,length=100)
  temp<-cos(xsmp)+2*sin(xsmp)
  return(temp)
}
y<-cos_sin(-pi,2*pi)
plot(y)
```
#雜記-8(要畫圖了喔!)
```{r}
from<- -pi
to<-2*pi
xsmp<-seq(from,to,length=100)
ys<-sin(xsmp)
plot(xsmp,ys,type="l")
yc<-cos(xsmp)
#一個參數lines(y)、2個參數lines(x,y)
lines(xsmp,yc)#疊圖
lines(ys)
#一個參數points(y)、2個參數points(x,y)
points(xsmp,ys)
```
#雜記-9(要畫圖了喔!)
```{r}
sum2<-function(x,y)
{
  return(x+y)
}
sum2(5:7,8)
```

#HW1
```{r}
#1.產生亂數300，平均5，標準差2的母體
x<-rnorm(300,5,2)
hist(x)
x<-sort(x)#sort()函數是對向量進行從小到大的排序
```

#HW2
```{r}
#2.在#1中的母體抽樣本100個，計算20個樣本統計量
x<-rnorm(300,5,2)
x<-sort(x)#在#1中的母體;sort()函數是對向量進行從小到大的排序
y<-as.integer(runif(20)*100)+1
s<-x[y]#1中的母體抽樣本100個，計算20個樣本統計量
s.sum<-summary(s)
print(s.sum[4])
hist(s)
```

#HW3
```{r}
#3.隨機產生1-300的號碼，共200
as.integer(runif(200)*300)+1 #+1的原因是他本來為0-299
```

#HW4
```{r}
#4.為#2的延伸
x<-rnorm(300,5,2)
x<-sort(x)#在#1中的母體
y<-as.integer(runif(20)*100)+1
s<-x[y]#1中的母體抽樣本100個，計算20個樣本統計量
s.sum<-summary(s)
print(s.sum[4])
hist(s)
s.mean<-s.sum[4]
s.sd<-sd(s)/sqrt(300)
print(s.sd)
print(s.mean)

s.conf<-c(-1.96*s.sd,1.96*s.sd)+s.mean#真正的母體平均值
s.conf
```

#HW1(改1)
```{r}
#1.產生亂數300
x<-rnorm(300,5,2)
y<-sort(x)#sort()函數是對向量進行從小到大的排序
#加寫↓
ssy<-summary(y)
typeof(ssy)#為向量
ssy[4]#為平均數
```

#HW1(改2)
```{r}
#1.產生亂數300
x<-rnorm(300)
s1<-sort(x)#sort()函數是對向量進行從小到大的排序
#把y<-sort(x)改成↓
s1
r1<-rank(x)#rank()函數返回的是對向量中每個數值對應的秩
r1
```

sort()函數是對向量進行從小到大的排序
rank()函數返回的是對向量中每個數值對應的秩
order()函數返回的值表示位置，依次對應的是向量的最小值、次小值、第三小值……最大值等（位置索引）
arrange()函數（需加載dplyr包）針對數據框，返回基於某列排序後的數據框，方便多重依據排序
