---
title: "11-5-1"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

## 雜記
```{r}
3^2
x<-c(1,23,4)
x
typeof(x)#意思代表向量

y<-c(1,23,4)
x||y#只要不是0都是ture
x|y#只要不是0都是ture
x
y
x&y#只要不是0都是ture
x&&y#只要不是0都是ture
x==y#只要不是0都是ture
x!=y#只要不是0都是ture

a<-c(0,34,33)
b<-c(0,34,2)
a|b
a&b

```

## 實數比較
```{r}
1==1
0.1==0.1
0.3==0.1+0.2#R的邏輯問題
0.3>=0.1+0.2
0.3<=0.1+0.2
all.equal(0.3,0.1+0.2)

```

## typeof、which
```{r}
A<-c("A","B","C","D")
typeof(A)
A[1]
C<-c("A","C","C","E")
C
A==C#只有TF
which(A==C)
A[which(A==C)]
# identical有效位數，是在做物件比較(型態)
```

## 字串
```{r}
letters#用來抽英文字母
pi
idx<-as.integer(runif(10)*26+1)
idx
letters[idx]
idx1<-c(27,idx)
idx1
letters[idx1]
```

## 
```{r}
x<-3#初始一個數字
x[2]<-5
x
r<-integer(0)#告訴x要放東西，可增加
```

## 
```{r}
list_data<-list("Red","Green",c(21,32,11),TRUE,51.23,119.1)
typeof(list_data)
list_data[1]
list_data[[5]]+list_data[[6]]
```

## 矩陣(1)
```{r}
matrix(c(3,9,5,1,-2,8),nrow=2)#向量轉矩陣
matrix(c(3,9,5,1,-2,8),ncol=2)#向量轉矩陣

xx<-"ddd"
xx<-'ddd'

`x 1`<-5#讓不合法變合法
`我是誰`<-5

list_data<-list(c("Jan","Fed","Mar"),matrix(c(3,9,5,1,-2,8),nrow=2),list("green",12,3))
list_data

list_data[[1]]
list_data[["a"]]
```

## 矩陣(2)
```{r}
x<-matrix(runif(9),nrow=3)
x[1,1]
x[1,3]
names(x)<-c("a","b","c")
x
x["a"]
x["b"]
x[["b"]]

rownames(x)<-c("a","b","c")
x
x["a",1]
names(x)<-NULL
x["a",1]
x["a",3]
colnames(x)<-c("x","y","z")
x
x["a","x"]
x["a",1]
```

## 矩陣(2-1統整)
```{r}
x<-matrix(runif(9),nrow=3)
rownames(x)<-c("a","b","c")
x["a",1]
colnames(x)<-c("x","y","z")
x["a",1]
```

## 矩陣(3運算)
```{r}
c1<-c(1,2,3)
c2<-c(4,5,6)
c3<-c(3,1)
m1<-cbind(c1,c2,c3)
m1#他會幫你又湊成3*3

#轉字
t(m1)
m1
m1[1,"c1"]

#反矩陣(先不要)

```

## 
```{r}
c1<-c(1,2,3)
c2<-c(4,5,6)
c3<-c(3,1)
m1<-cbind(c1,c2,c3)

#轉字
t(m1)
m1
m1[1,"c1"]

solve(m1)
m1%*%solve(m1)

b<-c(5,9,52)
solve(m1,b)
```

## 
```{r}
l1<-list(4,5,6)
v1<-c(3,3,3)
y<-c(v1,v1)
y
z<-c(v1,l1)
z
v<-unlist(z)
v
```

## 
```{r}

```

## 
```{r}

```